import sys
import uuid
import datetime
import random
sys.path.append("d:/docscope")

from backend.app.core.db import SessionLocal
from backend.app.models.models import (
    Organization, User, Membership, Role, Document, Folder, 
    UsageMetric, AuditLog, DocumentKeyword, DocumentEntity, DocumentSummary
)
from backend.app.core.security import get_password_hash

def seed_data():
    db = SessionLocal()
    try:
        # Check if user exists
        email = "demo@docscope.ai"
        user = db.query(User).filter(User.email == email).first()
        if not user:
            print("Creating demo user...")
            user = User(
                email=email,
                password_hash=get_password_hash("password123"),
                first_name="Demo",
                last_name="User"
            )
            db.add(user)
            db.commit()
            db.refresh(user)

        # Get or create Org
        org = db.query(Organization).first()
        if not org:
            org = Organization(name="Docscope Demo Org")
            db.add(org)
            db.commit()
            db.refresh(org)
            
            # Create Role
            role = Role(name="Organization Admin", org_id=org.id)
            db.add(role)
            db.commit()
            
            # Add membership
            mem = Membership(user_id=user.id, org_id=org.id, role_id=role.id)
            db.add(mem)
            db.commit()
        else:
            # ensure membership
            if not db.query(Membership).filter(Membership.user_id == user.id, Membership.org_id == org.id).first():
                role = db.query(Role).filter(Role.org_id == org.id, Role.name == "Organization Admin").first()
                if not role:
                    role = Role(name="Organization Admin", org_id=org.id)
                    db.add(role)
                    db.commit()
                mem = Membership(user_id=user.id, org_id=org.id, role_id=role.id)
                db.add(mem)
                db.commit()

        print("Seeding folders...")
        folders = [
            Folder(org_id=org.id, name="Financial Audits"),
            Folder(org_id=org.id, name="Legal Contracts"),
            Folder(org_id=org.id, name="Engineering Specs"),
        ]
        for f in folders:
            db.add(f)
        db.commit()

        print("Seeding documents...")
        doc_names = ["Q3 Financials.pdf", "Vendor Agreement.docx", "System Architecture.pdf", "Invoice_102.pdf"]
        now = datetime.datetime.now(datetime.timezone.utc)
        
        for idx, name in enumerate(doc_names):
            doc = Document(
                org_id=org.id,
                folder_id=folders[idx % len(folders)].id,
                name=name,
                storage_path=f"mock/{name}",
                status="completed",
                file_type=name.split(".")[-1],
                file_size=random.randint(100000, 5000000),
                created_at=now - datetime.timedelta(days=random.randint(0, 5))
            )
            db.add(doc)
            db.commit()
            db.refresh(doc)
            
            summary = DocumentSummary(
                document_id=doc.id,
                org_id=org.id,
                summary="This is a mock summary of the document automatically generated by the LLM pipeline. It highlights key sections and critical entities.",
                reading_time_minutes=random.randint(2, 15),
                complexity_score=random.uniform(0.3, 0.9),
                document_type="report"
            )
            db.add(summary)
            
            for kw in ["finance", "contract", "legal", "q3"]:
                db.add(DocumentKeyword(document_id=doc.id, org_id=org.id, keyword=kw, score=random.uniform(0.5, 0.99)))
            
        db.commit()

        print("Seeding metrics...")
        for i in range(7):
            dt = now - datetime.timedelta(days=i)
            db.add(UsageMetric(org_id=org.id, metric_type="api_tokens", value=random.randint(5000, 20000), created_at=dt))
            db.add(UsageMetric(org_id=org.id, metric_type="pages_rendered", value=random.randint(50, 300), created_at=dt))
            db.add(UsageMetric(org_id=org.id, metric_type="storage_bytes", value=random.randint(1000000, 50000000), created_at=dt))
        
        db.add(UsageMetric(org_id=org.id, metric_type="active_users", value=5, created_at=now))
        db.commit()

        print("Seeding audit logs...")
        actions = ["document.upload", "document.search", "chat.ask", "folder.create"]
        for _ in range(15):
            db.add(AuditLog(
                user_id=user.id,
                org_id=org.id,
                action=random.choice(actions),
                created_at=now - datetime.timedelta(hours=random.randint(1, 48))
            ))
        db.commit()
        
        print("Done seeding mock data.")
    except Exception as e:
        print("Error seeding data:", e)
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()
