export enum AppMode {
  PERSONAL = 'personal',
  TEAM = 'team',
  ENTERPRISE = 'enterprise',
}

export const CURRENT_APP_MODE = (process.env.NEXT_PUBLIC_APP_MODE as AppMode) || AppMode.PERSONAL;

export const features = {
  // Core Document Features
  ENABLE_AI_CHAT: true,
  ENABLE_OCR: true,
  ENABLE_SUMMARY: true,
  ENABLE_SEARCH: true,
  ENABLE_DUPLICATE_DETECTION: true,
  ENABLE_FOLDERS: true,
  ENABLE_TAGS: true,
  
  // Enterprise Modules
  ENABLE_VERSIONING: true,
  ENABLE_APPROVAL: CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_ACL: CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_TEAM: CURRENT_APP_MODE === AppMode.TEAM || CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_ORGANIZATION: CURRENT_APP_MODE === AppMode.TEAM || CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_NOTIFICATIONS: CURRENT_APP_MODE === AppMode.TEAM || CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_TASKS: CURRENT_APP_MODE === AppMode.TEAM || CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_AUDIT: CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_ANALYTICS: CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_MONITORING: CURRENT_APP_MODE === AppMode.ENTERPRISE,
  ENABLE_KNOWLEDGE_GRAPH: CURRENT_APP_MODE === AppMode.ENTERPRISE,
};
