apiVersion: v1
kind: Service
metadata:
  name: {{ include "docscope.fullname" . }}-frontend
  labels:
    {{- include "docscope.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "docscope.selectorLabels" . | nindent 4 }}
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docscope.fullname" . }}-frontend
  labels:
    {{- include "docscope.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "docscope.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "docscope.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "docscope.fullname" . }}-api:8001"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
