apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docscope.fullname" . }}-secrets
  labels:
    {{- include "docscope.labels" . | nindent 4 }}
type: Opaque
data:
  gemini-api-key: {{ .Values.config.geminiApiKey | b64enc | quote }}
  postgres-password: {{ .Values.config.dbPassword | b64enc | quote }}
