"""Sprint 13 Enterprise Workflow

Revision ID: 9a5a1b635432
Revises: 66ad7595ee9f
Create Date: 2026-07-03 23:57:38.656612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a5a1b635432'
down_revision: Union[str, None] = '66ad7595ee9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('document_comments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_comments_document_id'), 'document_comments', ['document_id'], unique=False)
    op.create_table('document_tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tasks_assigned_to'), 'document_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_document_tasks_document_id'), 'document_tasks', ['document_id'], unique=False)
    op.drop_table('usage_metrics_2026_07')
    op.drop_table('audit_logs_default')
    op.drop_table('usage_metrics_2026_08')
    op.drop_table('audit_logs_2026_08')
    op.drop_table('usage_metrics_default')
    op.drop_table('audit_logs_2026_07')
    op.alter_column('document_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_keywords', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_parse_elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('document_summaries_document_id_key', 'document_summaries', type_='unique')
    op.add_column('documents', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('failed_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'failed'::character varying"))
    op.alter_column('failed_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('failed_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('failed_jobs_task_id_key', 'failed_jobs', type_='unique')
    op.drop_index('ix_fj_status', table_name='failed_jobs')
    op.drop_index('ix_fj_task_id', table_name='failed_jobs')
    op.create_index(op.f('ix_failed_jobs_status'), 'failed_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_failed_jobs_task_id'), 'failed_jobs', ['task_id'], unique=True)
    op.alter_column('knowledge_graph_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_kge_org_id', table_name='knowledge_graph_edges')
    op.drop_index('ix_kge_source', table_name='knowledge_graph_edges')
    op.drop_index('ix_kge_target', table_name='knowledge_graph_edges')
    op.create_index(op.f('ix_knowledge_graph_edges_org_id'), 'knowledge_graph_edges', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_source_document_id'), 'knowledge_graph_edges', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_target_document_id'), 'knowledge_graph_edges', ['target_document_id'], unique=False)
    op.alter_column('ocr_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_metrics', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('processing_metrics', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('processing_metrics', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.drop_index('ix_pm_document_id', table_name='processing_metrics')
    op.drop_index('ix_pm_org_id', table_name='processing_metrics')
    op.drop_index('ix_pm_stage', table_name='processing_metrics')
    op.create_index(op.f('ix_processing_metrics_document_id'), 'processing_metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_metrics_org_id'), 'processing_metrics', ['org_id'], unique=False)
    op.drop_column('processing_metrics', 'ram_mb')
    op.drop_column('processing_metrics', 'created_at')
    op.add_column('text_embedding_chunks', sa.Column('section', sa.String(length=255), nullable=True))
    op.add_column('text_embedding_chunks', sa.Column('heading', sa.String(length=255), nullable=True))
    op.add_column('text_embedding_chunks', sa.Column('hierarchy', sa.Text(), nullable=True))
    op.add_column('text_embedding_chunks', sa.Column('parent_section', sa.String(length=255), nullable=True))
    op.alter_column('text_embedding_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_document_interactions', 'last_interaction_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_udi_document_id', table_name='user_document_interactions')
    op.drop_index('ix_udi_org_id', table_name='user_document_interactions')
    op.drop_index('ix_udi_user_id', table_name='user_document_interactions')
    op.create_index(op.f('ix_user_document_interactions_document_id'), 'user_document_interactions', ['document_id'], unique=False)
    op.create_index(op.f('ix_user_document_interactions_org_id'), 'user_document_interactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_document_interactions_user_id'), 'user_document_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_document_interactions_user_id'), table_name='user_document_interactions')
    op.drop_index(op.f('ix_user_document_interactions_org_id'), table_name='user_document_interactions')
    op.drop_index(op.f('ix_user_document_interactions_document_id'), table_name='user_document_interactions')
    op.create_index('ix_udi_user_id', 'user_document_interactions', ['user_id'], unique=False)
    op.create_index('ix_udi_org_id', 'user_document_interactions', ['org_id'], unique=False)
    op.create_index('ix_udi_document_id', 'user_document_interactions', ['document_id'], unique=False)
    op.alter_column('user_document_interactions', 'last_interaction_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_embedding_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('text_embedding_chunks', 'parent_section')
    op.drop_column('text_embedding_chunks', 'hierarchy')
    op.drop_column('text_embedding_chunks', 'heading')
    op.drop_column('text_embedding_chunks', 'section')
    op.add_column('processing_metrics', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('processing_metrics', sa.Column('ram_mb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_processing_metrics_org_id'), table_name='processing_metrics')
    op.drop_index(op.f('ix_processing_metrics_document_id'), table_name='processing_metrics')
    op.create_index('ix_pm_stage', 'processing_metrics', ['stage'], unique=False)
    op.create_index('ix_pm_org_id', 'processing_metrics', ['org_id'], unique=False)
    op.create_index('ix_pm_document_id', 'processing_metrics', ['document_id'], unique=False)
    op.alter_column('processing_metrics', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('processing_metrics', 'duration_ms',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('processing_metrics', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('processing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ocr_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_knowledge_graph_edges_target_document_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_source_document_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_org_id'), table_name='knowledge_graph_edges')
    op.create_index('ix_kge_target', 'knowledge_graph_edges', ['target_document_id'], unique=False)
    op.create_index('ix_kge_source', 'knowledge_graph_edges', ['source_document_id'], unique=False)
    op.create_index('ix_kge_org_id', 'knowledge_graph_edges', ['org_id'], unique=False)
    op.alter_column('knowledge_graph_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_failed_jobs_task_id'), table_name='failed_jobs')
    op.drop_index(op.f('ix_failed_jobs_status'), table_name='failed_jobs')
    op.create_index('ix_fj_task_id', 'failed_jobs', ['task_id'], unique=False)
    op.create_index('ix_fj_status', 'failed_jobs', ['status'], unique=False)
    op.create_unique_constraint('failed_jobs_task_id_key', 'failed_jobs', ['task_id'])
    op.alter_column('failed_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('failed_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('failed_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'failed'::character varying"))
    op.drop_column('documents', 'is_archived')
    op.create_unique_constraint('document_summaries_document_id_key', 'document_summaries', ['document_id'])
    op.alter_column('document_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_parse_elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_keywords', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('audit_logs_2026_07',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='audit_logs_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='audit_logs_2026_07_pkey')
    )
    op.create_table('usage_metrics_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='usage_metrics_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='usage_metrics_default_pkey')
    )
    op.create_table('audit_logs_2026_08',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='audit_logs_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='audit_logs_2026_08_pkey')
    )
    op.create_table('usage_metrics_2026_08',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='usage_metrics_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='usage_metrics_2026_08_pkey')
    )
    op.create_table('audit_logs_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='audit_logs_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='audit_logs_default_pkey')
    )
    op.create_table('usage_metrics_2026_07',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='usage_metrics_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name='usage_metrics_2026_07_pkey')
    )
    op.drop_index(op.f('ix_document_tasks_document_id'), table_name='document_tasks')
    op.drop_index(op.f('ix_document_tasks_assigned_to'), table_name='document_tasks')
    op.drop_table('document_tasks')
    op.drop_index(op.f('ix_document_comments_document_id'), table_name='document_comments')
    op.drop_table('document_comments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
